{% set version = "0.2.8" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: kececilayout/
  url: 
  sha256: 

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: python -m pip install --ignore-installed .
  number: 0

requirements:
  host:
    - python {{ python }}
    - numpy
    # Other build tools
  run:
    - python {{ python }}
    - numpy
    # Other runtime dependencies

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  summary: 'A deterministic node placement algorithm used in graph visualization. In this layout, nodes are arranged sequentially along a defined primary axis. Each subsequent node is then alternately offset along a secondary, perpendicular axis, typically moving to one side of the primary axis and then the other. Often, the magnitude of this secondary offset increases as nodes progress along the primary axis, creating a characteristic zig-zag or serpentine pattern.'
  description: |
    A deterministic node placement algorithm used in graph visualization. In this layout, nodes are arranged sequentially along a defined primary axis. Each subsequent node is then alternately offset along a secondary, perpendicular axis, typically moving to one side of the primary axis and then the other. Often, the magnitude of this secondary offset increases as nodes progress along the primary axis, creating a characteristic zig-zag or serpentine pattern.
  dev_url: https://github.com/WhiteSymmetry/kececilayout
  doc_url: https://github.com/WhiteSymmetry/kececilayout
  doc_source_url: https://github.com/WhiteSymmetry/kececilayout/blob/main/README.md
