{% set version = "0.5.6" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url:
  blake2b-256:
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    # Bu, paketin çalışması için GEREKLİ olan CONDA bağımlılıklarıdır.
    - python >=3.11
    - numpy
    - networkx
    - matplotlib-base
    - pycairo
    - cairocffi
    - cairo
    - python-igraph
    - rustworkx
    - networkit
    - python-louvain
    - graph-tool
    - numba

# DİKKAT: 'test:' bölümü bilinçli olarak kaldırılmıştır.

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: AGPL3.0-or-later
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
