{% set version = "0.3.2" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - numpy
    - setuptools
  run:
    - python >=3.10
    - numpy
    - networkx >=2.0
    - matplotlib >=3.0
    - rustworkx >=0.13.0
    - igraph >=0.10.0
    - python-louvain >=0.16
    # Graphillion'ı opsiyonel yap
    # - graphillion >=1.0  # Bu satırı kaldırın veya yorum yapın
    - pip
    - pip:
      - graphillion >=1.0

test:
  imports:
    - kececilayout

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets on a secondary
    axis, creating characteristic zig-zag patterns.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
  dev_url: https://github.com/WhiteSymmetry/kececilayout
