{% set version = "0.3.2" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - pip          # pip'in derleme ve test ortamlarında bulunması kritik
    - setuptools
    - numpy >=1.23,<2.0  # numpy versiyonunu sabitlemek iyi bir pratiktir
  run:
    - python >=3.10,<3.12
    - numpy >=1.23,<2.0
    - networkx >=2.0
    - matplotlib-base >=3.0
    - rustworkx >=0.13.0
    # 'graphillion' buradan kaldırıldı çünkü Conda kanallarında yok ve çözücüyü bozuyor.
    # Bu bağımlılığı aşağıda test aşamasında ve son kullanıcı için farklı yöneteceğiz.

test:
  # Testler çalışmadan ÖNCE çalıştırılacak komutlar
  commands:
    # Test ortamına graphillion'ı manuel olarak pip ile kur.
    - pip install graphillion >=1.0
  
  # Komutlar çalıştıktan sonra yapılacak import testleri
  imports:
    - kececilayout

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
