{% set version = "0.3.2" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy >=1.23,<2.0
  run:
    - python >=3.10,<3.12
    - numpy >=1.23,<2.0
    - networkx >=2.0
    - matplotlib-base >=3.0
    - rustworkx >=0.13.0
    # graphillion burada OLMAMALI, çünkü Conda kanallarında yok.

test:
  commands:
    # 1. Bağımlılığı kur (Bu adımın zaten çalıştığını biliyoruz)
    - pip install --no-cache-dir "graphillion>=1.0"

    # 2. Daha detaylı bir test komutu çalıştır.
    # 'python -c "..."' yerine tam bir python betiği çalıştırarak
    # hatanın tüm detaylarını (traceback) yakalayalım.
    - python -c "
try:
    import kececilayout
    print('kececilayout successfully imported')
except Exception as e:
    print('<<<<<<<<<< IMPORT FAILED, TRACEBACK: >>>>>>>>>>')
    import traceback
    traceback.print_exc()
    import sys
    sys.exit(1) # Hata koduyla çık ki build başarısız olsun

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
