{% set version = "0.3.2" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - pip
    - setuptools
    - numpy >=1.23,<2.0
  run:
    - python >=3.10,<3.12
    - numpy >=1.23,<2.0
    - networkx >=2.0
    - matplotlib-base >=3.0
    - rustworkx >=0.13.0
    # graphillion burada OLMAMALI, çünkü Conda kanallarında yok.

test:
  # 'imports' anahtarını tamamen kaldırıyoruz.
  # Tüm test mantığını 'commands' altına taşıyoruz.
  commands:
    # 1. ADIM: Test ortamının içine pip ile bağımlılığı AÇIKÇA kur.
    # --no-cache-dir, olası önbellek sorunlarını önler.
    - pip install --no-cache-dir "graphillion>=1.0"

    # 2. ADIM: Bağımlılık kurulduktan HEMEN SONRA, paketi import etmeyi dene.
    # Bu, asıl testimizdir. Eğer `kececilayout` veya onun bir bağımlılığı
    # bulunamazsa, bu komut hata verir ve build süreci durur.
    - python -c "import kececilayout"

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
