{% set version = "0.3.2" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - numpy
    - networkx
    - matplotlib-base
    - pycairo
    - cairocffi
    - cairo
    - graphillion  # <-- PİP YERİNE BURAYA EKLİYORUZ! conda-forge'dan gelecek.

test:
  # Artık özel bir test betiğine gerek yok. Sadece import etmesi yeterli.
  imports:
    - kececilayout

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: A deterministic node placement algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
