{% set version = "0.4.3" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/47/6e/9a8f47198d0f5cd1887278d3ad0ab145468f02ac9a89db06f32eda757a32/kececilayout-0.4.2.tar.gz
  sha256: 8930d8bdf8cbf17120431ae0f5fbe157ba681b79574940ec31b67f5819aa6ce3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    # Bu, paketin çalışması için GEREKLİ olan CONDA bağımlılıklarıdır.
    - python >=3.10
    - numpy
    - networkx
    - matplotlib-base
    - pycairo
    - cairocffi
    - cairo
    - python-igraph
    - rustworkx
    - networkit
    - python-louvain


# DİKKAT: 'test:' bölümü bilinçli olarak kaldırılmıştır.

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
