{% set version = "0.4.7" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/62/7b/eb77ccb991e56fd22406eb00803b271a39cbf5e16007d9d7a7d10a01d9de/kececilayout-0.4.7.tar.gz
  sha256: 94a2fdfc31d5d840f8dbf7fcada3e250c17633df3b4c4f1aeaa24fca88224364
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    # Bu, paketin çalışması için GEREKLİ olan CONDA bağımlılıklarıdır.
    - python >=3.10
    - numpy
    - networkx
    - matplotlib-base
    - pycairo
    - cairocffi
    - cairo
    - python-igraph
    - rustworkx
    - networkit
    - python-louvain
    - graph-tool

# DİKKAT: 'test:' bölümü bilinçli olarak kaldırılmıştır.

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
