{% set version = "0.4.5" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/5e/36/45354c04c3839885e89ebf838d7184ad16396b3761abcec776ce17a9daff/kececilayout-0.4.4.tar.gz
  sha256: 45fe87106280f9acb04cc393a79600261c32f86828ae214f8df0cc2647e67552

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    # Bu, paketin çalışması için GEREKLİ olan CONDA bağımlılıklarıdır.
    - python >=3.10
    - numpy
    - networkx
    - matplotlib-base
    - pycairo
    - cairocffi
    - cairo
    - python-igraph
    - rustworkx
    - networkit
    - python-louvain


# DİKKAT: 'test:' bölümü bilinçli olarak kaldırılmıştır.

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
