{% set version = "0.3.2" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - pip          # pip'in build ortamında bulunmasını sağla
    - setuptools
    - numpy
  run:
    - python >=3.8,<3.12
    - numpy
    - networkx >=2.0
    - matplotlib-base >=3.0
    - rustworkx >=0.13.0
    - graphillion >=1.0  # graphillion'ı normal bir bağımlılık olarak ekle

test:
  imports:
    - kececilayout

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: Advanced sequential-zigzag graph layout algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
