{% set version = "0.3.2" %}

package:
  name: kececilayout
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    # 'graphillion' buradan KALDIRILDI. Bu, conda çözücüsünün başarısız olmasını önler.
    - python >=3.10
    - numpy
    - networkx
    - matplotlib-base
    - pycairo
    - cairocffi
    - cairo

test:
  # Test ortamını kurmak için gerekenler. 'pip' burada kritik.
  requires:
    - python >=3.10
    - pip
    # Test ortamına, ana paketin conda bağımlılıklarını da ekleyelim.
    - numpy
    - networkx
    - matplotlib-base
    - pycairo
    - cairocffi
    - cairo

  # 'imports' yerine 'commands' kullanarak tam kontrol sağlıyoruz.
  commands:
    # ADIM 1: Test ortamına graphillion'ı manuel olarak pip ile kur.
    # Bu, conda çözücüsünü tamamen atlar.
    - pip install "graphillion>=1.0"

    # ADIM 2: Bağımlılık kurulduktan HEMEN SONRA, paketi import etmeyi dene.
    - python -c "import kececilayout"

about:
  home: https://github.com/WhiteSymmetry/kececilayout
  license: MIT
  license_file: LICENSE
  summary: A deterministic node placement algorithm
  description: |
    A deterministic node placement algorithm for graph visualization that arranges
    nodes sequentially along a primary axis with alternating offsets.
  doc_url: https://github.com/WhiteSymmetry/kececilayout
