[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock",
    "ruff"
    # Diğer test için gerekli kütüphaneler...
]
