# recipe-noarch-python.yaml
schema_version: 1

# this sets up "context variables" (in this case name and version) that
# can later be used in Jinja expressions
context:
  version: 0.7.1
  name: kececilayout

# top level package information (name and version)
package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/4b/9f/8eb4b0783f669fe4804e61bbc2a084ebbd4c03a4c8cabd76d8c38bbe28a1/kececilayout-0.7.1.tar.gz
  sha256: 0f7aab92b0c82a3682c865a2b8d67358eb1e9a8c6f729d5e705fb4afc9557e55

# build number (should be incremented if a new build is made, but version is not incrementing)
build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

# the requirements at build and runtime
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
   - python >=3.11
   - numpy
   - pip
   - numpy
   - pandas
   - scipy
   - matplotlib
   - graphillion
   - igraph
   - networkx
   - rustworkx
   - chess
   - networkit
   - seaborn
   - qiskit
   - numba
   - graph-tool

# tests to validate that the package works as expected
#tests:
#  requires: []  # veya boş liste
#  - python:
#      imports:
#        - kececilayout

# information about the package
about:
  homepage: https://github.com/WhiteSymmetry/kececilayout/
  license: AGPL-3.0-or-later
  summary: 'kececilayout'
  description: |
    kececilayout
  repository: https://github.com/WhiteSymmetry/kececilayout/
  documentation: https://github.com/WhiteSymmetry/kececilayout/

# the below is conda-forge specific!
extra:
  recipe-maintainers:
    - bilgi
