name: Publish to Anaconda Cloud

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CONDA_PKG_FORMAT: ".conda"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"  # Python 3.11 kullanıyoruz
          auto-activate-base: true
          channels: conda-forge,defaults
          channel-priority: strict
      
      - name: Prepare build environment
        run: |
          conda config --set always_yes true
          conda config --set changeps1 false
          conda update -q conda --all
          conda install -c conda-forge "python=3.11" conda-build conda-verify anaconda-client -y
          conda list
      
      - name: Build Conda package
        run: |
          mkdir -p ./conda_pkgs
          conda build . \
            --output-folder ./conda_pkgs \
            --format "$CONDA_PKG_FORMAT" \
            --python 3.11 \  # Spesifik Python versiyonu
            --numpy 1.23 \
            --debug
      
      - name: Upload to Anaconda Cloud
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda -t $ANACONDA_TOKEN upload \
            ./conda_pkgs/**/*$CONDA_PKG_FORMAT \
            --label main \
            --skip-existing
