name: Publish to Anaconda Cloud-conda-publish.yml

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CONDA_PKG_FORMAT: ".conda"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          auto-activate-base: true
          activate-environment: ""
          channels: conda-forge,defaults
      
      - name: Build environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda -n base
          conda install -c conda-forge conda-build conda-verify anaconda-client -y
          conda info
          conda list
      
      - name: Build Conda Package
        run: |
          conda build . --output-folder ./conda_pkgs --format "$CONDA_PKG_FORMAT" --debug
      
      - name: List built packages
        run: |
          ls -l ./conda_pkgs/
          find ./conda_pkgs/ -type f -name "*$CONDA_PKG_FORMAT"
      
      - name: Upload Package to Anaconda Cloud
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload ./conda_pkgs/**/*$CONDA_PKG_FORMAT --skip-existing
