name: Publish to Anaconda Cloud

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          auto-activate-base: false
          channels: conda-forge,defaults
          channel-priority: strict
      
      - name: Prepare build environment
        run: |
          conda config --set always_yes true
          conda config --set changeps1 false
          conda install -n base -c conda-forge "python=3.11" "conda-build" "conda-verify" "anaconda-client"
          conda clean --all -y
      
      - name: Build Conda package
        run: |
          mkdir -p ./conda_pkgs
          conda build . \
            --output-folder ./conda_pkgs || true \
            --python 3.11

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            test_success.log
            test_error.log
          if-no-files-found: ignore # Dosya bulunamazsa hata verme
      
      - name: Upload to Anaconda Cloud
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda -t $ANACONDA_TOKEN upload \
            ./conda_pkgs/noarch/*.tar.bz2 \
            --label main \
            --skip-existing
