name: Publish to Anaconda Cloud

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"  # or use a specific version like "py311_23.5.2-0"
          python-version: "3.11"
          auto-activate-base: true
          channels: conda-forge,defaults
          channel-priority: strict
      
      - name: Prepare build environment
        run: |
          conda config --set always_yes true
          conda config --set changeps1 false
          conda update -q conda conda-build --all
          conda install -c conda-forge "python=3.11" "conda-build=3.27.0" "conda-verify=3.4.2" anaconda-client -y
          conda clean --all -y
      
      - name: Build Conda package
        run: |
          mkdir -p ./conda_pkgs
          conda build . \
            --output-folder ./conda_pkgs \
            --python 3.11 \
            --numpy 1.23 \
            --no-test
      
      - name: Convert to .conda format
        run: |
          conda install -c conda-forge conda-package-handling -y
          find ./conda_pkgs -name "*.tar.bz2" -exec bash -c 'cph convert "{}" "$(dirname "{}")/$(basename "{}" .tar.bz2).conda"' \;
      
      - name: Upload to Anaconda Cloud
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda -t $ANACONDA_TOKEN upload \
            ./conda_pkgs/**/*.conda \
            --label main \
            --skip-existing
