name: Publish to Anaconda Cloud

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: "3.10"
          channels: conda-forge,defaults
          channel-priority: strict
      
      - name: Prepare build environment
        run: |
          conda install -n base conda-build anaconda-client -y
      
      - name: Build Conda package
        run: |
          conda build . --output-folder ./conda_pkgs

      - name: Upload to Anaconda Cloud
        # Bu adımı sadece bir release yayınlandığında çalıştır
        if: github.event_name == 'release' && success()
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda -t $ANACONDA_TOKEN upload \
            ./conda_pkgs/**/*.conda \
            --label main \
            --skip-existing
