name: Publish to Anaconda Cloud-conda-publish.yml

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CONDA_PKG_FORMAT: ".conda"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          auto-activate-base: true
          channels: conda-forge,defaults
          channel-priority: strict
      
      - name: Prepare build environment
        run: |
          conda config --set always_yes true --set changeps1 false
          conda update -q conda --all
          conda install -c conda-forge conda-build conda-verify anaconda-client -y
          conda info
          conda list
      
      - name: Build Conda package
        run: |
          conda build . \
            --output-folder ./conda_pkgs \
            --format "$CONDA_PKG_FORMAT" \
            --python 3.11 \
            --numpy 1.23 \
            --debug
      
      - name: Verify package
        run: |
          find ./conda_pkgs -name "*.conda" -exec conda verify {} \;
          ls -lh ./conda_pkgs/
      
      - name: Upload to Anaconda Cloud
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload \
            ./conda_pkgs/**/*$CONDA_PKG_FORMAT \
            --label main \
            --skip-existing \
            --force
