name: Conda-Build and Test Package

on:
  workflow_dispatch: # Manuel tetikleme
  release:
    types: [published] # Yeni release yayınlandığında tetikler

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: "3.11"
          channels: conda-forge,defaults
          channel-priority: strict
          activate-environment: base

      - name: Install Conda-Build and Anaconda-Client
        run: |
          conda install -n base conda-build anaconda-client -y
          # Anaconda client'ın PATH'te olduğundan emin ol
          echo "Anaconda client path:"
          which anaconda || echo "Anaconda not found in PATH"

      - name: Build the package
        run: |
          conda build . --output-folder ./conda_pkgs --variant-config-files ./conda_build_config.yaml
          mkdir -p dist
          find ./conda_pkgs -name "*.conda" -exec cp {} dist/ \;
          echo "Paketler dist klasörüne kopyalandı:"
          ls -l dist

      - name: Create a clean environment and install dependencies
        run: |
          conda create -n test-env -y python=3.11
          conda install -n test-env -y \
            numpy \
            networkx \
            rustworkx \
            networkit \
            python-igraph \
            python-louvain \
            matplotlib-base \
            pycairo \
            cairocffi \
            cairo

      - name: Install the built package into the test environment
        run: |
          PACKAGE_FILE=$(ls dist/*.conda | head -n 1)
          echo "Installing $PACKAGE_FILE"
          conda install -n test-env -y "$PACKAGE_FILE"
          
      - name: Run final import test and get traceback
        run: |
          echo "--- Installing graphillion in test-env via pip ---"
          conda run -n test-env pip install "graphillion>=1.0"
          
          echo "--- Attempting to import kececilayout ---"
          conda run -n test-env python -c "import kececilayout"

      - name: Upload to Anaconda Cloud
        if: success()
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          # 'find' komutu ile dist klasörünün içindeki tüm .conda dosyalarını bul
          PACKAGE_FILES=$(find dist -name "*.conda")

          # Token'ın varlığını kontrol et
          if [ -z "$ANACONDA_TOKEN" ]; then
            echo "HATA: ANACONDA_TOKEN bulunamadı! Lütfen GitHub repository settings'te ANACONDA_TOKEN secret'ını ekleyin."
            exit 1
          fi
          
          # Bulunan dosya(lar)ın varlığını kontrol et
          if [ -z "$PACKAGE_FILES" ]; then
            echo "HATA: Yüklenecek .conda dosyası bulunamadı! Build adımı başarısız olmuş olabilir."
            exit 1
          fi

          echo "Yüklenecek paketler bulundu:"
          echo "$PACKAGE_FILES"
          
          # Anaconda client'ın kurulu olduğundan emin ol
          which anaconda || conda install -n base -y anaconda-client
          
          # Base environment'ı activate et ve anaconda komutunu çalıştır
          conda run -n base anaconda -t $ANACONDA_TOKEN upload \
            $PACKAGE_FILES \
            --label main \
            --skip-existing
            
      - name: Cleanup test environment
        if: always()
        run: conda env remove -n test-env || true
