name: Publish to Anaconda Cloud-conda-publish

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CONDA_PKG_FORMAT: ".conda"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: "3.11"
          auto-activate-base: true
      
      - name: Build Conda Package
        run: |
          conda install -c conda-forge conda-build conda-verify -y
          conda build . --output-folder ./conda_pkgs --format "$CONDA_PKG_FORMAT"
      
      - name: Upload Package
        run: |
          conda install -c conda-forge anaconda-client -y
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload ./conda_pkgs/**/*$CONDA_PKG_FORMAT
